version: '3'

volumes:
  mongo-data:

services:
  smart-popup-backend:
    build: smart-popup-backend
    ports:
      - 8888:8888
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db